[package]
name = "one_clue"
version = "0.1.0"
authors = ["abyssparanoia <y.sugimoto.paranoia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
